FROM golang:1.16.3-alpine3.13 AS build
WORKDIR /src
COPY .. .
RUN go build -mod=vendor -o bin/cron ./cmd/cron

FROM alpine:3.13
COPY --from=build /src/bin/cron .
ENV PORT 8080
EXPOSE 8080
ENTRYPOINT ./cron
